window.PRODUCT_IMAGES = {
  "hard-ring-cookbook": { image: "images/product-originals/hard-ring-cookbook.jpg" },
  "deluxe-inner-nail-cookbook": { image: "images/product-originals/deluxe-inner-nail-cookbook.jpg" },
  "deluxe-outer-nail-cookbook": { image: "images/product-originals/deluxe-outer-nail-cookbook.png" },
  "butterfly-cookbook": { image: "images/product-originals/butterfly-cookbook.jpg" },
  "spiral-cookbook": { image: "images/product-originals/spiral-cookbook.jpg" },
  "laminated-spiral-cookbook": { image: "images/product-originals/laminated-spiral-cookbook.jpg" },
  "additional-inner-pages": { image: "images/product-originals/additional-inner-pages.jpg" },

  "laminated-menu": { image: "images/product-originals/laminated-menu.jpg" },
  "pvc-menu": { image: "images/product-originals/pvc-menu.jpg" },
  "photo-menu": { image: "images/product-originals/photo-menu.jpg" },
  "photo-paper-menu": { image: "images/product-originals/photo-menu.jpg" },
  "checklist-menu": { image: "images/product-originals/checklist-menu.jpg" },
  "multipart-form": { image: "images/product-originals/category-menu.png" },
  "indoor-light-film-menu": { image: "images/product-originals/indoor-light-film-menu.jpg" },
  "takeaway-card": { image: "images/product-originals/takeaway-card.jpg" },
  "voucher": { image: "images/product-originals/voucher.jpg" },
  "table-sign-menu": { image: "images/product-originals/table-sign-menu.jpg" },
  "banner-menu": { image: "images/product-originals/banner-menu.jpg" },
  "kt-board-menu": { image: "images/product-originals/kt-board-menu.jpg" },

  "backlit-fabric": { image: "images/product-originals/backlit-fabric.jpg" },
  "stretch-lightbox-fabric": { image: "images/product-originals/stretch-lightbox-fabric.jpg" },
  "canvas": { image: "images/product-originals/canvas.jpg" },
  "business-card": { image: "images/product-originals/business-card.jpg" },
  "flyer": { image: "images/product-originals/flyer.jpg" },
  "kt-board-poster": { image: "images/product-originals/kt-board-poster.jpg" },
  "sticker-poster": { image: "images/product-originals/sticker-poster.jpg" },
  "photo-poster": { image: "images/product-originals/photo-poster.jpg" },
  "banner": { image: "images/product-originals/banner.jpg" },
  "indoor-light-film": { image: "images/product-originals/indoor-light-film.jpg" },
  "static-cling": { image: "images/product-originals/static-cling.jpg" },
  "one-way-vision": { image: "images/product-originals/one-way-vision.jpg" },
  "car-sticker": { image: "images/product-originals/car-sticker.jpg" },
  "glass-lettering": { image: "images/product-originals/glass-lettering.png" },
  "copy-paper-print": { image: "images/product-originals/copy-paper-print.jpg" },
};
